inherit_gem:
  betterlint:
    - config/default.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Rails/EnvironmentVariableAccess:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'gemfiles/*'
