inherit_gem:
  betterlint:
    - config/default.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'gemfiles/*.gemfile'
    - 'Rakefile'
  NewCops: enable

Capybara/RSpec/PredicateMatcher:
  Enabled: false

Betterment/EnvironmentConfiguration:
  Enabled: false
