name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', '3.1', '3.2', '3.3']
        gemfile:
          - gemfiles/rspec_3.13.gemfile
          - gemfiles/rspec_3.12.gemfile
          - gemfiles/rspec_3.11.gemfile
          - gemfiles/rspec_3.10.gemfile
          - gemfiles/rspec_3.9.gemfile

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651
      env:
        BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      env:
        BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      run: bundle exec rake
