name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', '3.1', '3.2']
        gemfile:
          - gemfiles/rspec_3.9.gemfile
          - gemfiles/rspec_3.10.gemfile
          - gemfiles/rspec_3.11.gemfile
          - gemfiles/rspec_3.12.gemfile
          - gemfiles/rspec_3.13.gemfile
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      env:
        BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      env:
        BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      run: bundle exec rake
