name: Linter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651
      with:
        ruby-version: '3.2'
        bundler-cache: true
    - name: Run Linter
      run: bundle exec rubocop --parallel
